apiVersion: v1
kind: Service
metadata:
  name: client-server
  labels:
    app: client-server
spec:  
  ports:
  - protocol: TCP
    port: 51717
    targetPort: 51717
  selector:
    app: client-server  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client-server
  name: client-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-server
      name: client-server
    spec:  
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: riyazhu/unp:latest
        ports:
        - containerPort: 51717
        command: ["bash"]
        
      - name: client01
        image: riyazhu/unp:latest
        ports:
        - containerPort: 51717        
        command: ["bash"]  
        
      - name: client02
        image: riyazhu/unp:latest
        ports:
        - containerPort: 51717        
        command: ["bash"]